"""Debug/review checks used by convert.py when creating Excel output.

This file is intentionally lightweight and deterministic.  It does not call the
LLM.  It only looks at fields already present in labeled_cases.json, especially
Needs_Review / Review_Flags generated by review_checks.py.
"""

from __future__ import annotations

import ast
import re
from typing import Any

import pandas as pd


CASE_ID_COLUMN_CANDIDATES = (
    "case_id",
    "Case ID",
    "Case Name",
    "Case_Name",
    "case name",
    "CASE_ID",
    "Case",
)

LABEL_COLUMNS = (
    "CT_Original_GT",
    "CT_GT",
    "CTA_GT",
    "CTP_GT",
    "Combined_GT",
)


SUBDURAL_EXTRA_AXIAL_REVIEW_TERMS = (
    "subdural hematoma",
    "subdural haemorrhage",
    "subdural hemorrhage",
    "subdural blood",
    "subdural collection",
    "acute subdural",
    "sdh",
    "extra-axial hematoma",
    "extra-axial haemorrhage",
    "extra-axial hemorrhage",
    "extra-axial blood",
    "extraaxial hematoma",
    "extraaxial hemorrhage",
)

SUBARACHNOID_REVIEW_TERMS = (
    "subarachnoid hemorrhage",
    "subarachnoid haemorrhage",
    "subarachnoid blood",
    "sah",
)

SUBDURAL_SCAN_COLUMNS = (
    ("CT_Report", "CT report"),
    ("New_CT_Report", "sanitized CT report"),
    ("MRI_Report", "MRI report"),
    ("CTA_Report", "CTA brain-window text"),
    ("CTP_Report", "CTP context text"),
)

FALLBACK_ALLOWED_LABELS = {
    "NONE",
    "RMCA", "LMCA",
    "RACA", "LACA",
    "RPCA", "LPCA",
    "RPICA", "LPICA",
    "RVA", "LVA",
    "RICA", "LICA",
    "RCA", "LCA",
    "BA",
}


def _allowed_labels() -> set[str]:
    """Read config.ALLOWED_LABELS when available, otherwise use a safe fallback."""
    try:
        import Code.config as config  # type: ignore

        labels = getattr(config, "ALLOWED_LABELS", None)
        if isinstance(labels, (list, tuple, set)):
            return {str(label).strip().upper() for label in labels if str(label).strip()}
    except Exception:
        pass
    return set(FALLBACK_ALLOWED_LABELS)


def _normalize_column_name(name: Any) -> str:
    return re.sub(r"[^a-z0-9]", "", str(name).strip().lower())


def _find_column(df: pd.DataFrame, candidates: tuple[str, ...]) -> str | None:
    normalized_to_original = {_normalize_column_name(col): col for col in df.columns}
    for candidate in candidates:
        match = normalized_to_original.get(_normalize_column_name(candidate))
        if match is not None:
            return match
    return None


def _get(row: pd.Series, column_name: str, default: Any = "") -> Any:
    return row[column_name] if column_name in row.index else default


def _is_blank(value: Any) -> bool:
    if value is None:
        return True
    if isinstance(value, float) and pd.isna(value):
        return True
    text = str(value).strip()
    return text in {"", "[]", "{}", "nan", "NaN", "None", "NONE", "null", "NULL"}


def _truthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if pd.isna(value):
            return False
        return value != 0
    text = str(value).strip().lower()
    return text in {"true", "t", "yes", "y", "1"}


def _intish(value: Any) -> int:
    try:
        if value is None or (isinstance(value, float) and pd.isna(value)):
            return 0
        return int(float(str(value).strip()))
    except Exception:
        return 0


def _split_label_string(value: str) -> list[str]:
    text = value.strip()
    if not text:
        return []
    if text.startswith("[") and text.endswith("]"):
        try:
            parsed = ast.literal_eval(text)
            if isinstance(parsed, (list, tuple, set)):
                return [str(item) for item in parsed]
        except Exception:
            pass
    return re.split(r"[,;\n]+", text)


def _normalize_label_set(value: Any, *, remove_none_when_mixed: bool = True) -> set[str]:
    if value is None:
        return set()
    if isinstance(value, float) and pd.isna(value):
        return set()
    if isinstance(value, (list, tuple, set)):
        pieces = [str(item) for item in value]
    else:
        pieces = _split_label_string(str(value))

    labels: set[str] = set()
    for piece in pieces:
        label = str(piece).strip().strip('"\'[](){}').upper().replace(" ", "")
        if label and label not in {"NAN", "NULL", "NONE_"}:
            labels.add("NONE" if label in {"NEGATIVE", "NORMAL"} else label)

    if remove_none_when_mixed and "NONE" in labels and len(labels) > 1:
        labels.remove("NONE")
    return labels


def _raw_label_set_has_none_mixed(value: Any) -> bool:
    labels = _normalize_label_set(value, remove_none_when_mixed=False)
    return "NONE" in labels and len(labels) > 1


def _labels_text(labels: set[str]) -> str:
    if not labels:
        return "<blank>"
    if labels == {"NONE"}:
        return "NONE"
    order = [
        "RMCA", "LMCA", "RACA", "LACA", "RPCA", "LPCA",
        "RPICA", "LPICA", "BA", "RICA", "LICA", "RCA", "LCA",
    ]
    ordered = [label for label in order if label in labels]
    ordered.extend(sorted(label for label in labels if label not in ordered and label != "NONE"))
    return ", ".join(ordered)




def _compact_text(value: Any) -> str:
    text = str(value or "").lower().replace("/", " ")
    return re.sub(r"\s+", " ", text).strip()


def _term_regex(term: str) -> str:
    parts = [re.escape(part) for part in str(term).lower().split()]
    return r"\b" + r"\s+".join(parts) + r"\b"


def _sentences_for_review(text: Any) -> list[str]:
    compact = _compact_text(text)
    return [part.strip() for part in re.split(r"(?<=[.!?;])\s+", compact) if part.strip()]


def _sentence_has_negated_term(sentence: str, term: str) -> bool:
    term_re = _term_regex(term)
    negation_before = re.search(
        rf"\b(no|without|negative for|absence of|no evidence of|no findings of|not demonstrating|not showing)\b[^.;]{{0,80}}{term_re}",
        sentence,
    )
    negation_after = re.search(
        rf"{term_re}[^.;]{{0,50}}\b(absent|not seen|not present|not identified|not demonstrated|ruled out)\b",
        sentence,
    )
    return bool(negation_before or negation_after)


def _first_positive_hemorrhage_sentence(report: Any, terms: tuple[str, ...]) -> str:
    for sentence in _sentences_for_review(report):
        for term in terms:
            if re.search(_term_regex(term), sentence) and not _sentence_has_negated_term(sentence, term):
                return sentence
    return ""


def _short_quote(text: str, max_chars: int = 180) -> str:
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 3].rstrip() + "..."


def _subdural_extra_axial_reasons(row: pd.Series) -> list[str]:
    reasons: list[str] = []
    seen_sentences: set[str] = set()

    for column_name, display_name in SUBDURAL_SCAN_COLUMNS:
        report = _get(row, column_name, "")
        if _is_blank(report):
            continue

        subdural_sentence = _first_positive_hemorrhage_sentence(report, SUBDURAL_EXTRA_AXIAL_REVIEW_TERMS)
        if subdural_sentence and subdural_sentence not in seen_sentences:
            seen_sentences.add(subdural_sentence)
            reasons.append(
                "Subdural/extra-axial hemorrhage context detected in "
                f"{display_name}; review any subtle hypodensity or territory label because extra-axial blood is not an ischemic stroke territory. "
                f"Evidence: {_short_quote(subdural_sentence)}"
            )

        sah_sentence = _first_positive_hemorrhage_sentence(report, SUBARACHNOID_REVIEW_TERMS)
        report_text = _compact_text(report)
        has_subtle_hypodensity = "subtle hypodensity" in report_text or "questionable hypodensity" in report_text
        if sah_sentence and has_subtle_hypodensity and sah_sentence not in seen_sentences:
            seen_sentences.add(sah_sentence)
            reasons.append(
                "Subarachnoid hemorrhage plus subtle/questionable hypodensity detected; review before assigning a PCA/MCA/ACA ischemic territory label. "
                f"Evidence: {_short_quote(sah_sentence)}"
            )

    return reasons

def _row_has_positive_territory_label(row: pd.Series) -> bool:
    """Return True when any model label column contains a non-NONE label."""
    for column in LABEL_COLUMNS:
        labels = _normalize_label_set(_get(row, column, ""))
        if labels and labels != {"NONE"}:
            return True
    return False


def _review_priority_for_reason(row: pd.Series, reason: str) -> str:
    """Classify one review reason as red/high-priority or yellow/review-only.

    Red means the row is more likely to need immediate review because the label
    may be wrong, unstable, invalid, or contradicted by a high-risk condition.
    Yellow means the row is review-worthy but often just wording/noise.
    """
    text = _compact_text(reason)

    # High-risk clinical/context flags.  Subdural-only cases are yellow, but
    # subdural/SAH plus a positive territory label is red because that pattern
    # can create false ischemic labels from hemorrhage/edema/contusion context.
    if any(term in text for term in ("subdural", "extra axial", "extra-axial", "subarachnoid", "sah")):
        return "red" if _row_has_positive_territory_label(row) else "yellow"

    red_terms = (
        "answer mismatch",
        "low confidence vote share",
        "possible answers:",
        "combined_gt is none even though",
        "combined gt is none even though",
        "combined_gt was changed from none",
        "combined gt was changed from none",
        "code fallback",
        "case failed",
        "combined step failed",
        "failed during processing",
        "contains label s outside allowed_labels",
        "contains label outside allowed_labels",
        "mixes none with a positive territory label",
        "ct label changed after sanitization",
        "label changed after sanitization",
        "but reasoning appears to cite",
        "common cervical carotid",
        "invalid label",
    )
    if any(term in text for term in red_terms):
        return "red"

    # These are often false positives from phrasing like "only LMCA, omitting
    # LICA".  Keep them visible, but do not make them red unless another red
    # reason is also present for the same case.
    yellow_terms = (
        "reasoning appears to exclude omit label",
        "reasoning appears to exclude/omit label",
        "uses an only phrase supporting",
        "needs_review is true",
        "review_flag_count",
        "pica label is present",
        "possible cta ctp contamination terms",
    )
    if any(term in text for term in yellow_terms):
        return "yellow"

    return "yellow"


def _dedupe_reasons(reasons: list[str]) -> list[str]:
    seen: set[str] = set()
    deduped: list[str] = []
    for reason in reasons:
        text = str(reason).strip()
        if text and text not in seen:
            deduped.append(text)
            seen.add(text)
    return deduped



def _parse_review_flag_list(value: Any) -> list[str]:
    """Parse Review_Flags/Review_Flags_Red/Review_Flags_Yellow cells safely.

    JSON-to-Excel conversion may store these as actual lists, Python-list-like
    strings, JSON-list-like strings, or plain text.  Return one reason per flag
    so red/yellow priority can be applied to each reason independently.
    """
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return []
    if isinstance(value, (list, tuple, set)):
        return [str(item).strip() for item in value if str(item).strip()]

    text = str(value).strip()
    if text in {"", "[]", "{}", "nan", "NaN", "None", "NONE", "null", "NULL"}:
        return []

    if text.startswith("[") and text.endswith("]"):
        try:
            parsed = ast.literal_eval(text)
            if isinstance(parsed, (list, tuple, set)):
                return [str(item).strip() for item in parsed if str(item).strip()]
        except Exception:
            pass

    # Fallback for newline-separated or semicolon-separated review reasons.
    parts = [part.strip() for part in re.split(r"\n+|;\s+(?=[A-Z][A-Za-z _-]*:)", text) if part.strip()]
    return parts if parts else [text]

def _collect_review_reasons_for_row(row: pd.Series, output_df: pd.DataFrame) -> list[str]:
    """Collect deterministic review reasons for one generated-output row.

    Prefer explicit Review_Flags_Red / Review_Flags_Yellow when present.  If the
    JSON only has the older Review_Flags field, parse it into individual flags
    rather than treating the whole list as one giant reason.
    """
    allowed_labels = _allowed_labels()
    reasons: list[str] = []

    # Newer review_checks.py writes split red/yellow lists.  Preserve the exact
    # individual reasons so they can be classified independently by priority.
    explicit_red_flags = _parse_review_flag_list(_get(row, "Review_Flags_Red", ""))
    explicit_yellow_flags = _parse_review_flag_list(_get(row, "Review_Flags_Yellow", ""))
    if explicit_red_flags or explicit_yellow_flags:
        reasons.extend(explicit_red_flags)
        reasons.extend(explicit_yellow_flags)
    else:
        review_flags = _parse_review_flag_list(_get(row, "Review_Flags", ""))
        if review_flags:
            reasons.extend(review_flags)
        else:
            # Keep old fallback behavior for older JSONs that only had booleans.
            review_flag_count = _intish(_get(row, "Review_Flag_Count", 0))
            if _truthy(_get(row, "Needs_Review", False)):
                reasons.append("Needs_Review is true")
            if review_flag_count > 0:
                reasons.append(f"Review_Flag_Count is {review_flag_count}")

    # Subdural / extra-axial hemorrhage review: useful for old JSON files that
    # were generated before review_checks.py added this flag.
    reasons.extend(_subdural_extra_axial_reasons(row))

    # Sanitization-related review: useful because CT can change after the
    # sanitizer removes CTA/CTP wording and reruns CT labeling.
    if _truthy(_get(row, "CT_Report_Was_Sanitized", False)):
        original_ct = _normalize_label_set(_get(row, "CT_Original_GT", ""))
        final_ct = _normalize_label_set(_get(row, "CT_GT", ""))
        if original_ct and final_ct and original_ct != final_ct:
            reasons.append(
                "CT label changed after sanitization: "
                f"{_labels_text(original_ct)} -> {_labels_text(final_ct)}"
            )

    # Basic label sanity checks.
    for column in LABEL_COLUMNS:
        if column not in output_df.columns:
            continue
        labels = _normalize_label_set(_get(row, column, ""), remove_none_when_mixed=False)
        if not labels:
            continue
        invalid = sorted(label for label in labels if label not in allowed_labels)
        if invalid:
            reasons.append(f"{column} contains label(s) outside ALLOWED_LABELS: {', '.join(invalid)}")
        if _raw_label_set_has_none_mixed(_get(row, column, "")):
            reasons.append(f"{column} mixes NONE with a positive territory label")

    # Combined NONE while a modality is positive can be legitimate in special
    # cases, but it is worth review because it often means the final Combined
    # step dropped evidence.
    combined = _normalize_label_set(_get(row, "Combined_GT", ""))
    modality_labels = [
        _normalize_label_set(_get(row, "CT_GT", "")),
        _normalize_label_set(_get(row, "CTA_GT", "")),
        _normalize_label_set(_get(row, "CTP_GT", "")),
    ]
    if combined == {"NONE"} and any(labels and labels != {"NONE"} for labels in modality_labels):
        reasons.append("Combined_GT is NONE even though at least one modality label is positive")

    return _dedupe_reasons(reasons)


def find_review_excel_rows_by_severity(output_df: pd.DataFrame) -> dict[str, dict[int, list[str]]]:
    """Return review rows split into red and yellow priority buckets.

    Shape:
        {
            "red": {excel_row_number: [high_priority_reason, ...]},
            "yellow": {excel_row_number: [review_reason, ...]},
        }

    If the same row has both red and yellow reasons, convert.py should give red
    display priority while still listing both kinds of reasons in the review
    sheet.
    """
    buckets: dict[str, dict[int, list[str]]] = {"red": {}, "yellow": {}}

    for df_index, row in output_df.iterrows():
        excel_row_number = int(df_index) + 2
        reasons = _collect_review_reasons_for_row(row, output_df)
        if not reasons:
            continue

        red_reasons: list[str] = []
        yellow_reasons: list[str] = []
        for reason in reasons:
            if _review_priority_for_reason(row, reason) == "red":
                red_reasons.append(reason)
            else:
                yellow_reasons.append(reason)

        if red_reasons:
            buckets["red"][excel_row_number] = _dedupe_reasons(red_reasons)
        if yellow_reasons:
            buckets["yellow"][excel_row_number] = _dedupe_reasons(yellow_reasons)

    red_count = len(buckets["red"])
    yellow_only_count = len(set(buckets["yellow"]) - set(buckets["red"]))
    if red_count or yellow_only_count:
        print(
            f"Highlighted {red_count} high-priority review row(s) red and "
            f"{yellow_only_count} review-only row(s) yellow."
        )

    return buckets


def find_strange_excel_rows_with_reasons(output_df: pd.DataFrame) -> dict[int, list[str]]:
    """Backward-compatible wrapper returning all review rows/reasons.

    Older convert.py versions treat all returned rows as yellow.  Newer
    convert.py versions should call find_review_excel_rows_by_severity().
    """
    buckets = find_review_excel_rows_by_severity(output_df)
    all_rows = sorted(set(buckets["red"]) | set(buckets["yellow"]))
    return {
        row_number: _dedupe_reasons(
            buckets["red"].get(row_number, []) + buckets["yellow"].get(row_number, [])
        )
        for row_number in all_rows
    }


def find_strange_excel_rows(output_df: pd.DataFrame) -> set[int]:
    """Backward-friendly wrapper returning only row numbers."""
    return set(find_strange_excel_rows_with_reasons(output_df).keys())
